name: General

on: pull_request

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "~16"
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(npx yarn cache dir)"
      - name: Initialize Yarn module cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Go and Dependencies
        uses: ./.github/actions/install-go-and-deps
        with:
          go-version: "~1.17"
      - name: Initialize tool binary cache
        id: tools-cache
        uses: actions/cache@v2
        with:
          path: tools/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
      - name: Make Mage
        run: make tools/bin/mage
        if: steps.tools-cache.outputs.cache-hit != 'true'
      - name: Editor config
        uses: snow-actions/eclint@v1.0.1
        # TODO: Fix EditorConfig errors and remove
        # https://github.com/TheThingsNetwork/lorawan-stack/issues/2723
        continue-on-error: true
      - name: Check headers
        run: tools/bin/mage headers:check
      - name: Fix common spelling mistakes
        run: tools/bin/mage dev:misspell
      - name: Check for diff
        run: tools/bin/mage git:diff
