name: Go Code

on:
  pull_request:
    paths:
      - ".github/workflows/go.yml"
      - "*.go"
      - ".revive.toml"
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - "pkg/**"
      - "!pkg/webui/**"
      - "pkg/webui/**.go"
      - "tools/**"

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Go and Dependencies
        uses: ./.github/actions/install-go-and-deps
        with:
          go-version: "~1.17"
      - name: Initialize tool binary cache
        id: tools-cache
        uses: actions/cache@v2
        with:
          path: tools/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
      - name: Make Mage
        run: make tools/bin/mage
        if: steps.tools-cache.outputs.cache-hit != 'true'
      - name: Format code
        run: tools/bin/mage go:fmt
      - name: Lint code
        run: tools/bin/mage go:lint
      - name: Generate i18n messages
        run: tools/bin/mage go:messages
      - name: Generate allowed fieldmask paths
        run: tools/bin/mage jsSDK:allowedFieldMaskPaths
      - name: Check for diff
        run: tools/bin/mage git:diff

  test:
    name: Tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        ports:
          - "5432/tcp"
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        # TODO: Support latest Redis (7.x is not supported, see https://github.com/TheThingsNetwork/lorawan-stack/issues/5416)
        image: redis:6.2
        ports:
          - "6379/tcp"
    timeout-minutes: 15
    steps:
      - name: Create ttn_lorawan_is_test DB
        uses: docker://postgres
        env:
          PGPASSWORD: root
        with:
          entrypoint: /usr/bin/createdb
          args: -h postgres -U root ttn_lorawan_is_test
      - name: Create ttn_lorawan_is_store_test DB
        uses: docker://postgres
        env:
          PGPASSWORD: root
        with:
          entrypoint: /usr/bin/createdb
          args: -h postgres -U root ttn_lorawan_is_store_test
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Go and Dependencies
        uses: ./.github/actions/install-go-and-deps
        with:
          go-version: "~1.17"
      - name: Initialize tool binary cache
        id: tools-cache
        uses: actions/cache@v2
        with:
          path: tools/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
      - name: Make Mage
        run: make tools/bin/mage
        if: steps.tools-cache.outputs.cache-hit != 'true'
      - name: Test binary execution
        run: tools/bin/mage go:testBinaries
      - name: Test code
        env:
          SQL_DB_ADDRESS: localhost:${{ job.services.postgres.ports['5432'] }}
          SQL_DB_AUTH: "root:root"
          REDIS_ADDRESS: localhost:${{ job.services.redis.ports['6379'] }}
          TEST_REDIS: "1"
          TEST_SLOWDOWN: "8"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}
          GCP_CREDENTIALS: ${{ secrets.GCP_TEST_CREDENTIALS }}
          TEST_BUCKET: lorawan-stack-test-bucket
        run: tools/bin/mage go:test
      - name: Check for diff
        run: tools/bin/mage git:diff
