name: JS Code

on:
  pull_request:
    paths:
      - ".github/workflows/js.yml"
      - "config/**"
      - "!config/stack/ttn-lw-stack.yml"
      - "Makefile"
      - "package.json"
      - "pkg/webui/**"
      - "!pkg/webui/**.go"
      - "sdk/js/**"
      - "tools/**"
      - "cypress/**"
      - "yarn.lock"

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "~16"
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(npx yarn cache dir)"
      - name: Initialize Yarn module cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Go and Dependencies
        uses: ./.github/actions/install-go-and-deps
        with:
          go-version: "~1.17"
      - name: Initialize tool binary cache
        id: tools-cache
        uses: actions/cache@v2
        with:
          path: tools/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
      - name: Make Mage
        run: make tools/bin/mage
        if: steps.tools-cache.outputs.cache-hit != 'true'
      - name: Install JS SDK dependencies
        run: tools/bin/mage jsSDK:deps
      - name: Generate JS SDK allowed field masks
        run: tools/bin/mage jsSDK:allowedFieldMaskPaths jsSDK:deviceFieldMasks
      - name: Build JS SDK
        run: tools/bin/mage jsSDK:clean jsSDK:build
      - name: Install JS dependencies
        run: tools/bin/mage js:deps
      - name: Generate JS translations
        run: tools/bin/mage js:translations js:backendTranslations
      - name: Lint JS SDK code
        run: tools/bin/mage -v jsSDK:lint
      - name: Lint frontend code
        run: tools/bin/mage -v js:lint
      - name: Check for diff
        run: tools/bin/mage git:diff

  test:
    name: Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "~16"
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(npx yarn cache dir)"
      - name: Initialize Yarn module cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Go and Dependencies
        uses: ./.github/actions/install-go-and-deps
        with:
          go-version: "~1.17"
      - name: Initialize public folder cache
        id: public-cache
        uses: actions/cache@v2
        with:
          path: public
          key: public-cache-${{ hashFiles('pkg/webui/**') }}-${{ hashFiles('sdk/js/**/*.js', 'sdk/js/generated/*.json') }}-${{ hashFiles('config/webpack.config.babel.js') }}-${{ hashFiles('yarn.lock', 'sdk/js/yarn.lock')}}
      - name: Initialize tool binary cache
        id: tools-cache
        uses: actions/cache@v2
        with:
          path: tools/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
      - name: Make Mage
        run: make tools/bin/mage
        if: steps.tools-cache.outputs.cache-hit != 'true'
      - name: Install JS SDK dependencies
        run: tools/bin/mage jsSDK:deps
      - name: Install JS dependencies
        run: tools/bin/mage js:deps
      - name: Test JS SDK code
        run: tools/bin/mage jsSDK:test
      - name: Test frontend code
        run: tools/bin/mage js:test
      - name: Check for diff
        run: tools/bin/mage git:diff
