name: API

on:
  pull_request:
    paths:
      - ".github/workflows/proto.yml"
      - "**.proto"
      - "tools/**"

jobs:
  protos:
    name: Generate protos
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Go and Dependencies
        uses: ./.github/actions/install-go-and-deps
        with:
          go-version: "~1.17"
      - name: Initialize tool binary cache
        id: tools-cache
        uses: actions/cache@v2
        with:
          path: tools/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
      - name: Make Mage
        run: make tools/bin/mage
        if: steps.tools-cache.outputs.cache-hit != 'true'
      - name: Generate protos
        run: tools/bin/mage proto:clean proto:all
      - name: Check for diff
        run: tools/bin/mage git:diff
